services:
  envoy1.30.1:
    image: envoyproxy/envoy:v1.30.1
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml"]
    ports:
      - "8080:8080" # echo
      - "8081:8081" # grpc
      - "9901:9901" # admin
    volumes:
      - ./config/envoy1.30.1.yaml:/etc/envoy/envoy.yaml
  service:
    build:
      context: ./src/csharp/Echo/
  echo-grpc:
    build:
      context: ./src/go/echo-grpc/
  reverse-grpc:
    build:
      context: ./src/go/reverse-grpc/
