services:
  envoy:
    image: envoyproxy/envoy:v1.30.4
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml"]
    ports:
      - "8080:8080" # echo
      - "9901:9901" # admin
    volumes:
      - ./config/envoy1.30.4.yaml:/etc/envoy/envoy.yaml
  service:
    build:
      context: ./src/csharp/Echo/
  echo-grpc:
    build:
      context: ./src/go/echo-grpc/
  reverse-grpc:
    build:
      context: ./src/go/reverse-grpc/
  prometheus:
    image: prom/prometheus:v2.45.6
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - envoy
  grafana:
    image: grafana/grafana:9.5.20
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
  k6:
    image: grafana/k6:0.52.0
    command: ["run", "/scripts/service.js"]
    # command: ["run", "/scripts/echo-grpc.js"]
    # command: ["run", "/scripts/reverse-grpc.js"]
    depends_on:
      - envoy
      - service
      - echo-grpc
      - reverse-grpc
      - grafana
    ports:
      - "6565:6565"
    volumes:
      - ./k6:/scripts
