services:
  envoy1.30.1:
    image: envoyproxy/envoy:v1.30.1
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml"]
    ports:
      - "8080:8080"
    volumes:
      - ./config/envoy1.30.1.yaml:/etc/envoy/envoy.yaml

  service:
    build:
      context: ./src/csharp/Echo/
