apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: envoy-http2
spec:
  targetGroupARN: <targetgroup>
  targetType: ip
  serviceRef:
    name: envoy-svc
    port: 10000
  networking:
    ingress:
      - from:
          - ipBlock:
              cidr: 0.0.0.0/0
        ports:
          - port: 10000
            protocol: TCP
